me: CI Maven Checkstyle Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    #- name: Build with Maven
    #  run: mvn -B package --file pom.xml
    
    #- name: Install Maven
      #run: sudo apt-get install maven -y
      
    - name: Build with Maven and generate Checkstyle report
      run: mvn clean verify checkstyle:checkstyle --file pom.xml 
      continue-on-error: true
          
    - name: Archive Checkstyle report
      uses: actions/upload-artifact@v2
      with:
        name: checkstyle-report
        path: target/site/checkstyle.html

